import type { Metadata, Viewport } from "next";
import { Public_Sans, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import LabelContainer from "labelcontainer";
import { labelData } from "./constants/label";
import Banner from "./components/Banner/Banner";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 0.7,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Create My Website",
  description: "Generated by create-next-website",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  LabelContainer.getInstance().setLabels(labelData);
  const lsInstance = LabelContainer.getInstance();
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${publicSans.variable} antialiased`}>
        <div id="root">
          <Header />
          <Banner msg={lsInstance.getLabel("banner_text")} />
          <div className={"flex justify-center grow h-scren"}>
            <div className="flex grow flex-col max-w-[1440px] px-8">{children}</div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
