import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import LabelContainer from "labelcontainer";
import { labelData } from "./constants/label";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 0.7,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Create My Website",
  description: "Generated by create-next-website",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  LabelContainer.getInstance().setLabels(labelData);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div id="root">
          <Header />
          <div className={"flex grow px-8 w-screen h-scren"}>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
